name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'

      - name: Grant Permission to Execute
        run: chmod +x ./gradlew

      - name: Build debug apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload apk to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token:${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app.apk
          tag: ${{ github.ref }}
          overwrite: true